version: "3"

services:
  node1:
    build:
      dockerfile: Dockerfile
      context: .
    command: bash -c "python hadcoin_node_5001.py"
    ports:
      - 5001:5001
      - 10001:10001
    env_file:
      - .env
    volumes:
      - ./app:/app:cached

  node2:
    build:
      dockerfile: Dockerfile
      context: .
    command: bash -c "python hadcoin_node_5002.py"
    ports:
      - 5002:5002
      - 10002:10002
    env_file:
      - .env
    volumes:
      - ./app:/app:cached
  node3:
    build:
      dockerfile: Dockerfile
      context: .
    command: bash -c "python hadcoin_node_5003.py"
    ports:
      - 5003:5003
      - 10003:10003
    env_file:
      - .env
    volumes:
      - ./app:/app:cached